export const CLICK_SQUARE_ONLINE = 'CLICK_SQUARE_ONLINE';
export const GET_USERNAME_BOARDONLINE = 'GET_USERNAME_BOARDONLINE';
export const GET_THE_STARTING_POSITION = 'GET_THE_STARTING_POSITION';
export const LOSE_GAME = 'LOSE_GAME';
export const CLEAR_STATE = 'CLEAR_STATE';
export const TIE = 'ITE';
export const REQUEST_TIE = 'REQUEST_TIE';
export const NEW_GAME = 'NEW_GAME';
