export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const SHOW_LOADING_WHEN_FIND_MATCH = 'SHOW_LOADING_WHEN_FIND_MATCH';
export const HIDE_LOADING_WHEN_FIND_MATCH = 'HIDE_LOADING_WHEN_FIND_MATCH';
