export const HANDLE_ONCHANGE_EMAIL_FIELD_IN_REGISTER =
  'HANDLE_ONCHANGE_EMAIL_FIELD_IN_REGISTER';
export const HANDLE_ONCHANGE_PASSWORD_FIELD_IN_REGISTER =
  'HANDLE_ONCHANGE_PASSWORD_FIELD_IN_REGISTER';
export const HANDLE_ONCHANGE_REPASSWORD_FIELD_IN_REGISTER =
  'HANDLE_ONCHANGE_REPASSWORD_FIELD_IN_REGISTER';
